#!/bin/bash

#******************************************************#
#                                                      #
#          Script for listing iterations in            #
#              Gaussian 16 output files                #
#                                                      #
#        Benjamin Jackson, Auburn University           #
#                 baj0040@auburn.edu                   #
#                                                      #
#               Updated:  07/27/2022                   #
#                                                      #
#******************************************************#

main(){
##Default Values which are customizable##
DEFAULT=ComplexList #Default search type if not specified
G16_SUFFIX=log
LINES=5 #Default number of lines to display

if [[ $# -lt 1 ]]; then ${DEFAULT};
	elif [[ $# -eq 1 ]] && [[ $1 != "-h" ]] && [[ $1 != "-s" ]] && [[ $1 != "-c" ]]; then LINES=$1; ${DEFAULT};
	else
		while getopts "hscl:" option; do
			case $option in
				h) HelpFn; exit;;
				s) SimpleList;;
				c) ComplexList;;
				l) LENGTH=$OPTARG
			esac
		done
fi
}
BGreen='\033[1;32m'
BRed='\033[1;31m'
Blue='\033[0;36m'
Yellow='\033[0;33m'
EndColor='\033[0m'
LGreen='\033[0;32m'
Red='\033[0;31m'
LBlue='\033[0;34m'
SPACER="    "
ComplexList(){
for FILE in $(ls . | awk -e "/[[:alnum:]]*.${G16_SUFFIX}[_]?[:alnum::punct:]*/ {print}"); do
	JOBTYPE=$(grep '#' ${FILE} | head -1 | awk -F'!' '{print $1}')
	#echo ${JOBTYPE}
	if [[ $(echo ${JOBTYPE} | grep -cE 'stable=opt') -eq 1 ]]; then
		echo -e "${Blue}${FILE}${EndColor} ${LBlue}-- Stability Check${EndColor}"
		#echo -e " Stability Check"
		Search;
		if [[ $( grep -c 'Normal term' ${FILE} ) == 1 ]]; then echo -e " ${LGreen}${SPACER}***Finished***${EndColor}";
		elif [[ $( grep -c 'Error termination' ${FILE} ) != 0 ]]; then echo -e "${SPACER}${Red}***Error Termination***${EndColor}";
		else echo -e " ${Yellow}${SPACER}***Stability check incomplete***${EndColor}";
		fi
			#Later, add a functionality for printing the stability comments
	elif [[ $(echo ${JOBTYPE} | grep -cE '[[:blank:]]opt') -eq 1 ]]; then
		echo -e "${Blue}${FILE}${EndColor} ${LBlue}-- Geometry Optimization${EndColor}"
		Search;
		if [[ $( grep -c 'Error termination' ${FILE} ) != 0 ]]; then echo -e "${SPACER}***${Red}Error Termination${EndColor}***" ; fi
		if [[ $(echo ${JOBTYPE} | grep -cE 'freq') -eq 1 ]]; then
			if [[ $( grep -c 'Normal term' ${FILE} ) == 1 ]]; then echo -e "${SPACER}***${Yellow}Converged, running frequencies...${EndColor}***" ;
				elif [[ $( grep -c 'Normal term' ${FILE} ) == 2 ]]; then echo -e "${SPACER}***${LGreen}Finished${EndColor}***" ; fi
		elif [[ $( grep -c 'Normal term' ${FILE} ) == 1 ]]; then echo -e "${SPACER}***${LGreen}Finished${EndColor}***" ;
		else echo -e "${SPACER}***${Yellow}Incomplete${EndColor}***"
		fi
	else
		echo -e "${Blue}${FILE}${EndColor} ${LBlue}-- Single Point Energy${EndColor}"
		Search;
		if [[ $( grep -c 'Error termination' ${FILE} ) != 0 ]]; then echo -e "${SPACER}***${Red}Error Termination${EndColor}***";
		elif [[ $( grep -c 'Normal term' ${FILE} ) == 2 ]]; then echo -e "${SPACER}***${LGreen}Finished${EndColor}***" ;
		else echo -e "${SPACER}***${Yellow}Incomplete${EndColor}***"
		fi
	fi
	#echo -e "---------------------"
done
}
Search(){
if [[ $(grep -c 'SCF Done:' ${FILE}) -gt 0 ]]; then
	grep -E 'SCF Done:' ${FILE} | tail -${LINES}
elif [[ $(grep -Ec 'E[UR]MP2' ${FILE}) -gt 0 ]]; then
	grep -E 'E[UR]+MP2' ${FILE} | tail -${LINES}
else echo -e " No iterations completed"
fi
}
SimpleList(){
for FILE in $(ls . | awk -e '/[:alnum:]*.log[_]?[:alnum::punct:]*/ {print}'); do
	echo ${FILE}
	Search;
	echo -e "---"
done
}

HelpFn(){
echo -e "
Script for listing iterations of Gaussian16 output files
      Options:
       -h    |   Help, display this current usage guide
       -c    |   Use the complex search function- this will identify the type of calculation run
       -s    |   Use the simple search function- this is analagous to EM's pren
       -l    |   Specify the number of lines to print

If you do not specify -s or -c the default will be used.
If you wish to use your default you can quickly specify the number of lines printed this way:
$(echo $0) #

Your current defaults are:
       Search Type      =   ${DEFAULT}
       Lines            =   ${LINES}
       Gaussian Suffix  =   ${G16_SUFFIX}
You can change this in $(echo $0)

EXAMPLES:
$(echo $0) -c -l 10
$(echo $0) 10
"
}
main "$@"; exit
